### ISSUE TITLE
parseJavaInheritance() does not work when the code is untidy

### ISSUE THREAD

**Issue by martin-zemek** [qoretechnologies/qorus-vscode#226]
for example, this does not work:
```
class A
    extends B {
}
```
`symbol.extends` is not there

**Comment by omusil24** [comment]
Fixed in a0bfdca64645a2684cf4d4d1b7f01a57aa3e671b.

**Comment by martin-zemek** [comment]
it still does not work, for example when the opening compound bracket { is not at the same line as the base class name then the the numbers in symbol.extends.range are wrong
```
class A extends B
        {
}

```
We need the exact ranges of both class name and base class name to be able to rename them according the user edit action in the webview.
All possibilities should  work, no matter how weird, for example
class
  A

        extends

  B
      {
               }
