### ISSUE TITLE
[BUG] errors managing service methods

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#592]
in the latest build from `develop`, for a Python service with two methods, `init` and `test`:
* adding a third method to the Python service results in a request timeout after clicking `Submit`:
<img width="1950" alt="Screen Shot 2020-07-18 at 8 31 14 AM" src="https://user-images.githubusercontent.com/13432105/87846567-1be60180-c8d1-11ea-99f5-81fde8487212.png">
* resetting and going back to the code and then the service and clicking `Submit` again removes the `test` method source and YAML entry too

I had similar issues with Java, so I do not think this is Python-specific.

**Comment by martin-zemek** [comment]
there are errors both on backend and frontend

the frontend issue: on adding a method the frontend sends back only the newly added method in the method list

**Comment by davidnich** [comment]
another error scenario with a Qore service:
1) create a service with 2 methods, `init` and `get`
2) from the source code page, click on `Edit Service` code lens control
3) go back to the source code - the `get` method has disappeared

if you then click the `Add Method` code lens control and readd the `get` method, going back to the service reveals that the `init` method has now disappeared

**Comment by martin-zemek** [comment]
@davidnich I can reproduce the three-step issue only if I click `Edit Method `in the step 2 (not `Edit Service`).

So, it seems that `Edit Method` and `Add Method` have the same issue: only the edited/added method is sent from the frontend to the backend and therefore only that one method is saved.

**Comment by martin-zemek** [comment]
The issue happens only when editing is opened from a code lens.

**Comment by Foxhoundn** [comment]
@davidnich I belive this is fixed in develop now, can you give it a try please?

**Comment by davidnich** [comment]
@Foxhoundn @martin-zemek still failing as reported on Slack on Fri - to reproduce:
- open `demos/chatbot/chatbot-demo-v1.0.qsd.yaml`
- click `Submit` twice to get to the service source
- the `categorize_input` method disappears from the YAML

**Comment by martin-zemek** [comment]
is it still happening?

**Comment by davidnich** [comment]
@martin-zemek no, it looks like it's fixed; I'll close the issue

**Comment by martin-zemek** [comment]
do you mean that you didn't submit the service between steps 2. and 3.?

**Comment by davidnich** [comment]
cannot reproduce
